# Generated by Django 4.1.7 on 2023-05-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
