# Generated by Django 4.1.7 on 2023-05-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
