# Generated by Django 4.1.7 on 2023-05-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0006_article_tag_delete_product_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
